spring.application.name=Url-Shortener-System-Desigin
server.port=8080

# MongoDB
spring.mongodb.uri=${MONGO_URI}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}